version: "3.7"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    networks:
      - nginx-network
    ports:
      - 80:80
      - 443:443
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
      - "com.centurylinklabs.watchtower.enable=false"

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=d4bes2000@gmail.com
    networks:
      - nginx-network
    depends_on:
      - nginx-proxy
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/Chicago
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 0 * * ?

  personal-website-nginx:
    image: darrylforbes/personal-website-nginx
    environment:
      - VIRTUAL_HOST=www.darrylforbes.me,darrylforbes.me
      - LETSENCRYPT_HOST=www.darrylforbes.me,darrylforbes.me
    networks:
      - personal-website-network
      - nginx-network

  firefly-iii:
    image: fireflyiii/core:latest
    env_file:
      - firefly-iii.env
    environment:
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=money.darrylforbes.me
      - LETSENCRYPT_HOST=money.darrylforbes.me
    volumes:
      - firefly-iii-upload:/var/www/html/storage/upload
    networks:
      - firefly-iii-network
      - nginx-network
    depends_on:
      - firefly-iii-db

  firefly-iii-db:
    image: postgres:13-alpine
    env_file:
      - firefly-iii.env
    volumes:
      - firefly-iii-db:/var/lib/postgresql/data
    networks:
      - firefly-iii-network
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  kesey-nginx:
    image: darrylforbes/kesey-nginx
    environment:
      - VIRTUAL_HOST=kesey.darrylforbes.me
      - LETSENCRYPT_HOST=kesey.darrylforbes.me
    networks:
      - kesey-network
      - nginx-network

  open-when-backend:
    image: darrylforbes/open-when-backend
    env_file: ./open-when.env
    expose:
      - "8000"
    depends_on:
      - open-when-db
    networks:
      - open-when-network

  open-when-db:
    image: postgres:12.6
    env_file: ./open-when.env
    volumes:
      - open-when-data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - open-when-network
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  open-when-nginx:
    image: darrylforbes/open-when-nginx
    environment:
      - VIRTUAL_HOST=openwhen.darrylforbes.me
      - LETSENCRYPT_HOST=openwhen.darrylforbes.me
    depends_on:
      - open-when-backend
      - open-when-db
    networks:
      - open-when-network
      - nginx-network

networks:
  nginx-network:
    name: nginx-network
  personal-website-network:
    name: personal-website-network
  firefly-iii-network:
    name: firefly-iii-network
  kesey-network:
    name: kesey-network
  open-when-network:
    name: open-when-network

volumes:
  certs:
  vhost:
  html:
  acme:
  firefly-iii-upload:
  firefly-iii-db:
  open-when-data:
