version: "3.7"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    networks:
      - nginx-network
    ports:
      - 80:80
      - 443:443
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    environment:
      - DEFAULT_EMAIL=d4bes2000@gmail.com
    networks:
      - nginx-network
    depends_on:
      - nginx-proxy

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true

  happy-appy-api:
    image: darrylforbes/happy-appy-api
    env_file:
      - ./happy-appy.env.prod
    networks:
      - happy-appy-network

  happy-appy-frontend:
    image: darrylforbes/happy-appy-frontend
    networks:
      - happy-appy-network

  happy-appy-nginx:
    image: darrylforbes/happy-appy-nginx
    networks:
      - happy-appy-network
      - nginx-network
    depends_on:
      - happy-appy-api
      - happy-appy-frontend

  personal-website-nginx:
    image: darrylforbes/personal-website-nginx
    networks:
      - personal-website-network
      - nginx-network
    expose:
      - 80

networks:
  nginx-network:
    name: nginx-network
  happy-appy-network:
    name: happy-appy-network
  personal-website-network:
    name: personal-website-network

volumes:
  certs:
  vhost:
  html:
